intl: Fix clang -Wunused-but-set-variable on plural.c
Clang warns that '__gettextnerrs' set but not used:

  intl/plural.c:1034:9: error: variable '__gettextnerrs' set but not used
  [-Werror,-Wunused-but-set-variable]
      int yynerrs = 0;
        ^

Since the file is auto-generated, suppress the warning with a compiler
flag.